// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmZXQ-r4Z0c84-S46wTAmtoMQoxZDD0c',
    appId: '1:88556216006:web:1f28095ba7663d262341c7',
    messagingSenderId: '88556216006',
    projectId: 'lapor-book-cbf3c',
    authDomain: 'lapor-book-cbf3c.firebaseapp.com',
    storageBucket: 'lapor-book-cbf3c.appspot.com',
    measurementId: 'G-SESNKJ7FCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Tpvt5LgW75YvNW2ETwNPYuBWpYqJjOU',
    appId: '1:88556216006:android:a30c7d95b98e3a4e2341c7',
    messagingSenderId: '88556216006',
    projectId: 'lapor-book-cbf3c',
    storageBucket: 'lapor-book-cbf3c.appspot.com',
  );
}
